name: Automate Invitation

on:
  issues:
    types: [labeled]

jobs:
  handle_label:
    runs-on: ubuntu-latest

    steps:
      - name: Check if Label is 'invite me to the community'
        id: check_label
        run: |
          if [[ "${{ github.event.label.name }}" != "invite me to the community" ]]; then
            echo "Label is not 'invite me to the community'. Exiting."
            exit 0
          fi

      - name: Create Issue in Support Repository
        id: create_issue
        if: ${{ steps.check_label.outcome == 'success' }}
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          script: |
            const issue = context.payload.issue;
            const { owner, repo } = context.repo;
            const response = await github.rest.issues.create({
              owner: 'Recode-Hive',
              repo: 'Support',       
              title: issue.title,
              body: issue.body,
              labels: ['invite me to the community'],
            });
            core.setOutput('issue_number', response.data.number);

      - name: Close Original Issue in StackOverflow Repository
        if: ${{ steps.check_label.outcome == 'success' }}
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          script: |
            const issue = context.payload.issue;
            await github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue.number,
              state: 'closed'
            });

      - name: Invite on Label
        if: ${{ steps.check_label.outcome == 'success' }}
        uses: vj-abigo/invite-on-label@v1.2
        with:
          organization: Recode-Hive
          label: invite me to the community
          repo-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          comment: |
            <b>Invitation sent to join the GitHub Organisation. Welcome to the community ðŸŽ‰</b><br><br>
            Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see. You can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/Recode-Hive/people<br><br>
            Tips for practising:<br><br>
            Customise your GitHub profile, here is a course on that: https://www.udemy.com/course/make-your-github-profile-stand-out/<br>
            Practice repo, instructions on how to add your name to the README https://github.com/Recode-Hive/hacktoberfest-practice<br>
            Remember contributing to open source is not just about code, it's about collaboration, communication and adding value<br>
            I hope that helps
        env:
          INVITE_TOKEN: ${{ secrets.INVITE_TOKEN }}
